#!/bin/sh

ROOT_DIR="dockerfiles"
PWD=$(pwd)
REPOSITORY=${PWD#*"$ROOT_DIR/"}
PLATFORM_OS="linux"
PLATFORM_ARCH="${1:-}"
ENABLE_CACHE="${2:-0}"
DOCKERFILE_PATH="."

if [ "$PLATFORM_ARCH" = "" ]; then
    PLATFORM_ARG=""
    TAG_ARG="-t $REPOSITORY"
else
    PLATFORM_ARG="--platform $PLATFORM_OS/$PLATFORM_ARCH"
    TAG_ARG="-t $REPOSITORY:$PLATFORM_ARCH"
fi

if [ "$ENABLE_CACHE" = "0" ]; then
    NO_CACHE_ARG="--no-cache"
else
    NO_CACHE_ARG=""
fi

DOCKER_BUILD_CMD="\
    docker buildx build \
    $PLATFORM_ARG \
    $TAG_ARG \
    $DOCKERFILE_PATH \
    $NO_CACHE_ARG"

echo $DOCKER_BUILD_CMD
$DOCKER_BUILD_CMD
