#!/bin/sh

TARGET_ARCH="amd64"
ENABLE_CACHE="${1:-0}"
ENABLE_EMULATOR_CMD="docker run --privileged --rm tonistiigi/binfmt --install $TARGET_ARCH"
BUILD_SCRIPT_CMD="./build $TARGET_ARCH $ENABLE_CACHE"

BINFMT_PATH="/proc/sys/fs/binfmt_misc/"
PARALLELS_ROSETTA_REG_NAME="RosettaLinux"
PARALLELS_ROSETTA_SUPPORT=$(ls $BINFMT_PATH | grep $PARALLELS_ROSETTA_REG_NAME)
if [ -z "$PARALLELS_ROSETTA_SUPPORT" ]; then
    echo "Using QEMU"
    echo $ENABLE_EMULATOR_CMD
    $ENABLE_EMULATOR_CMD
else
    echo "Using Rosetta (Parallels)"
fi

echo $BUILD_SCRIPT_CMD
$BUILD_SCRIPT_CMD
