#!/bin/sh

ROOT_DIR="dockerfile_templates"
PWD=$(pwd)
REPOSITORY=${PWD#*"$ROOT_DIR/"}
PLATFORM_OS="linux"
PLATFORM_ARCH="${1:-}"
INTERACTIVE_ARG="-i"
TTY_ARG="-t"
RM_ARG="--rm"
NETWORK_ARG="--network=host"
CONTAINER_EXEC_CMD="/bin/bash"
MOUNT_ARG="-v $HOME:/home/docker"

# Enable X11 forwarding
if [ "$DISPLAY" != "" ]; then
    XSOCK=/tmp/.X11-unix
    XAUTH=/tmp/.docker.xauth
    touch $XAUTH
    xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
    XAUTH_ARG="-v $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH"
    DISPLAY_ARG="-e DISPLAY=$DISPLAY"
fi

if [ "$PLATFORM_ARCH" = "" ]; then
    PLATFORM_ARG=""
    IMAGE="$REPOSITORY"
else
    PLATFORM_ARG="--platform $PLATFORM_OS/$PLATFORM_ARCH"
    IMAGE="$REPOSITORY:$PLATFORM_ARCH"
fi

DOCKER_RUN_CMD="\
    docker run \
    $INTERACTIVE_ARG \
    $TTY_ARG \
    $RM_ARG \
    $PLATFORM_ARG \
    $NETWORK_ARG \
    $MOUNT_ARG \
    $XAUTH_ARG \
    $DISPLAY_ARG \
    $IMAGE \
    $CONTAINER_EXEC_CMD"

echo $DOCKER_RUN_CMD
$DOCKER_RUN_CMD
