#!/bin/sh

TARGET_ARCH="amd64"
ENABLE_EMULATOR_CMD="docker run --privileged --rm tonistiigi/binfmt --install $TARGET_ARCH"
RUN_SCRIPT_CMD="./run $TARGET_ARCH"

echo $ENABLE_EMULATOR_CMD
$ENABLE_EMULATOR_CMD

echo $RUN_SCRIPT_CMD
$RUN_SCRIPT_CMD
